# Set working language
language: c

# It's needed to install g++4.8 correctly
dist: trusty

before_install:
    - pip install --user cpp-coveralls

# Additional packages
addons:
    apt:
        packages:
        - libgtest-dev
        - g++-4.8

# Finish GTest installation
before_script: cd /usr/src/gtest && sudo env "PATH=$PATH" cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && cd -

# Build and test script
script: mkdir -p _build && cd _build && cmake -D PLATFORM=pc  .. && make && test/test

after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
